### ISSUE TITLE
No URL is visited before attempting to login

### ISSUE THREAD

**Issue by metaperl** [786raees/automated-selenium#1]
In [the getting started sample](https://github.com/786raees/automated-selenium#getting-started) no URL is visited before logging in. This is not possible. It would be nice to add visiting a URL so that we can see how to access selenium methods from automated-selenium.

**Comment by metaperl** [comment]
the `driver.get()` method is [what is needed](https://selenium-python.readthedocs.io/getting-started.html#simple-usage).

**Comment by 786raees** [comment]
I thought that developer will do this in the constructor of the page I have also updated the docs.
please check and thanks for informing me.
